version: '2'

networks:
  sb:
   driver: bridge

services:
  mongodb:
    image: 'bitnami/mongodb:latest'
    environment:
      MONGO_INITDB_ROOT_USERNAME: packsendmeappdb
      MONGO_INITDB_ROOT_PASSWORD: sjbvpc07
    networks:
      - sb
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  zookeeper:
    image: confluentinc/cp-zookeeper:3.2.1
    hostname: zookeeper
    networks:
     - sb
    ports:
      - '32181:32181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      
  redis-master:
    image: 'bitnami/redis:latest'
    ports:
     - "6379:6379"
    volumes:
     - $PWD/redis-data:/var/lib/redis
     - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
     - REDIS_REPLICATION_MODE=master
     - REDIS_PASSWORD=packsendme_master_password
    volumes:
      - '/path/to/redis-persistence:/bitnami'
    networks:
       - sb

kafka1:
    image: confluentinc/cp-kafka:3.2.1
    networks:
      - sb
    ports:
      - '9092:9092'
      - '29092:29092'
    depends_on:
      - zookeeper

    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:19092,EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://localhost:19092,EXTERNAL://167.172.152.184:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      # Following line is needed for Kafka versions 0.11+
      # in case you run less than 3 Kafka brokers in your
      # cluster because the broker config
      # `offsets.topic.replication.factor` (default: 3)
      # is now enforced upon topic creation
      # KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  mongodb_data_container:

 