server:
  port: 9093

eureka:
  instance:
    hostname: localhost
    port: 9091
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000

spring:
   data:
      mongodb.host: 192.241.133.13
      mongodb.port: 27017
      mongodb.uri: mongodb://192.241.133.13/packsendDB
      mongodb.repositories.enabled: true

    authserver:
        hostname: http://localhost:9092
    security:
      oauth2:
        resource:
          userInfoUri: ${authserver.hostname}/user