server:
  port: 9091

eureka:
  instance:
    hostname: eureka
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000
spring:
  thymeleaf:
    enabled: false