server:
  port: 9100

eureka:
  instance:
    hostname: 192.241.133.13
    port: 9091
    leaseRenewalIntervalInSeconds: 5   
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000

security:
    oauth2:
        client:
            access-token-validity-seconds: 1800
            authorized-grant-types: password,refresh_token
            client-id: admin
            client-secret: $2a$10$jJFbSMGC2xsOqIlYYLqRouBDGRsvnP.egfdw3MutRXzHdhNoNnBA6
            resource-ids: resources
            scope: read,write

redis:
  cache:
    roadwayBRE_SA: Roadway-SouthAmerica-BRE
    airwayBRE_SA: Airway-SouthAmerica-BRE
    maritimewayBRE_SA: Maritimeway-SouthAmerica-BRE
    executeBRE_SA: Execute-SouthAmerica-BRE
    tollsfuelBRE_SA: TollsFuel-SouthAmerica-BRE
    financeCostDeliveryBRE_SA: FinanceCostDelivery-SouthAmerica-BRE
    truckBRE_SA: TruckBRE-SouthAmerica-BRE
    
spring:
   redis:
      host: 167.172.152.184
      port: 6379
      password: packsendme_master_password