server:
  port: 9099

eureka:
  instance:
    hostname: 192.241.133.13
    port: 9091
    leaseRenewalIntervalInSeconds: 5   
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000

security:
    oauth2:
        client:
            access-token-validity-seconds: 1800
            authorized-grant-types: password,refresh_token
            client-id: admin
            client-secret: $2a$10$jJFbSMGC2xsOqIlYYLqRouBDGRsvnP.egfdw3MutRXzHdhNoNnBA6
            resource-ids: resources
            scope: read,write

api:
   tolls:
      direction: https://maps.googleapis.com/maps/api/directions/json?origin={origin}&destination={destination}&key={my}
      distance: https://maps.googleapis.com/maps/api/distancematrix/json?origins={origin}&destinations={destination}&key={my}
      key: AIzaSyDt5pgW0boE_KhyVZHpNAh

spring:
   data:
      mongodb.host: 167.172.152.184
      mongodb.port: 27017
      mongodb.uri: mongodb://167.172.152.184/dbpacksendme
      mongo.repositories.enabled: true
